@url = http://localhost:5000/products-module
@categoryId = 0e811788-3168-4ffd-bb14-011edb05cf83

###
POST {{url}}/categories
Content-Type: application/json

{
    "name" : "New Category 2"
}

###
GET {{url}}/categories/{{categoryId}}

###
GET {{url}}/categories