@url = http://localhost:5000/products-module
@categoryId = 8364e211-d8b1-4bb6-9b3e-1526b2365dad
@productId = 8364e211-d8b1-4bb6-9b3e-1526b2365dad

###
POST {{url}}/products
Content-Type: application/json

{
    "productName" : "New Product",
    "categoryId": "{{categoryId}}"
}

###
GET {{url}}/products/{{productId}}

